### ISSUE TITLE
"gulp" failed,how to fix it?tks

### ISSUE THREAD

**Issue by luckypoem** [ducksoupdev/gulp-site-generator#17]
hi.

root@AR:/usr/local/gulp-site-generator# gulp
[10:31:48] Using gulpfile /usr/local/gulp-site-generator/gulpfile.js
[10:31:48] Starting 'sass'...
[10:31:48] Starting 'copy-fonts'...
[10:31:48] Starting 'copy-css'...
[10:31:48] Starting 'concat-js'...
[10:31:48] Starting 'image-min'...
[10:31:48] Finished 'copy-fonts' after 43 ms
[10:31:48] Finished 'copy-css' after 43 ms
[10:31:48] Finished 'concat-js' after 45 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/gulp-site-generator/node_modules/mozjpeg/vendor/cjpeg ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
root@AR:/usr/local/gulp-site-generator#

**Comment by ducksoupdev** [comment]
Hi, apologies for the delay in replying. Is this still an issue? Do you have a full stacktrace you can post? How did you install the generator - by submodule?
